- hosts: localhost
  become: true
  tasks: 
  - name: Install packages
    pacman: name={{item}}
    with_items:
      - parted
        
  - name: Setup partitions
    parted:
      device: /dev/sda
      number: 1
      state: present
      flags: ['esp']
      part_start: 1MiB
      part_end: 513MiB
      
  - filesystem:
      fstype: vfat
      dev: /dev/sda1
      