- hosts: localhost
  become: true
  tasks: 
  - name: Install parted
    pacman: parted
  - name: Setup partitions
    parted:
      device: /dev/sda
      number: 1
      state: present
      part_start: 1MiB
      part_end: 513MiB
      
  - filesystem:
      fstype: fat32
      dev: /dev/sda1
      